// Code generated by protoc-gen-go. DO NOT EDIT.
// source: customer.proto

package customer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Id                   int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string               `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string               `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Addresses            []*Request_Address   `protobuf:"bytes,5,rep,name=addresses,proto3" json:"addresses,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_customer_67035383523f7620, []int{0}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Request) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Request) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Request) GetAddresses() []*Request_Address {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *Request) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type Request_Address struct {
	Street               string   `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City                 string   `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	State                string   `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Zip                  string   `protobuf:"bytes,4,opt,name=zip,proto3" json:"zip,omitempty"`
	IsShippingAddress    bool     `protobuf:"varint,5,opt,name=isShippingAddress,proto3" json:"isShippingAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request_Address) Reset()         { *m = Request_Address{} }
func (m *Request_Address) String() string { return proto.CompactTextString(m) }
func (*Request_Address) ProtoMessage()    {}
func (*Request_Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_customer_67035383523f7620, []int{0, 0}
}
func (m *Request_Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_Address.Unmarshal(m, b)
}
func (m *Request_Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_Address.Marshal(b, m, deterministic)
}
func (dst *Request_Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_Address.Merge(dst, src)
}
func (m *Request_Address) XXX_Size() int {
	return xxx_messageInfo_Request_Address.Size(m)
}
func (m *Request_Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Request_Address proto.InternalMessageInfo

func (m *Request_Address) GetStreet() string {
	if m != nil {
		return m.Street
	}
	return ""
}

func (m *Request_Address) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Request_Address) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Request_Address) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

func (m *Request_Address) GetIsShippingAddress() bool {
	if m != nil {
		return m.IsShippingAddress
	}
	return false
}

type Response struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_customer_67035383523f7620, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type ListFilter struct {
	Keyword              string   `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListFilter) Reset()         { *m = ListFilter{} }
func (m *ListFilter) String() string { return proto.CompactTextString(m) }
func (*ListFilter) ProtoMessage()    {}
func (*ListFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_customer_67035383523f7620, []int{2}
}
func (m *ListFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListFilter.Unmarshal(m, b)
}
func (m *ListFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListFilter.Marshal(b, m, deterministic)
}
func (dst *ListFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListFilter.Merge(dst, src)
}
func (m *ListFilter) XXX_Size() int {
	return xxx_messageInfo_ListFilter.Size(m)
}
func (m *ListFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_ListFilter.DiscardUnknown(m)
}

var xxx_messageInfo_ListFilter proto.InternalMessageInfo

func (m *ListFilter) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "customer.Request")
	proto.RegisterType((*Request_Address)(nil), "customer.Request.Address")
	proto.RegisterType((*Response)(nil), "customer.Response")
	proto.RegisterType((*ListFilter)(nil), "customer.ListFilter")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CustomerClient is the client API for Customer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CustomerClient interface {
	List(ctx context.Context, in *ListFilter, opts ...grpc.CallOption) (Customer_ListClient, error)
	Create(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type customerClient struct {
	cc *grpc.ClientConn
}

func NewCustomerClient(cc *grpc.ClientConn) CustomerClient {
	return &customerClient{cc}
}

func (c *customerClient) List(ctx context.Context, in *ListFilter, opts ...grpc.CallOption) (Customer_ListClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Customer_serviceDesc.Streams[0], "/customer.Customer/List", opts...)
	if err != nil {
		return nil, err
	}
	x := &customerListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Customer_ListClient interface {
	Recv() (*Request, error)
	grpc.ClientStream
}

type customerListClient struct {
	grpc.ClientStream
}

func (x *customerListClient) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *customerClient) Create(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/customer.Customer/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomerServer is the server API for Customer service.
type CustomerServer interface {
	List(*ListFilter, Customer_ListServer) error
	Create(context.Context, *Request) (*Response, error)
}

func RegisterCustomerServer(s *grpc.Server, srv CustomerServer) {
	s.RegisterService(&_Customer_serviceDesc, srv)
}

func _Customer_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListFilter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CustomerServer).List(m, &customerListServer{stream})
}

type Customer_ListServer interface {
	Send(*Request) error
	grpc.ServerStream
}

type customerListServer struct {
	grpc.ServerStream
}

func (x *customerListServer) Send(m *Request) error {
	return x.ServerStream.SendMsg(m)
}

func _Customer_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customer.Customer/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).Create(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Customer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "customer.Customer",
	HandlerType: (*CustomerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Customer_Create_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "List",
			Handler:       _Customer_List_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "customer.proto",
}

func init() { proto.RegisterFile("customer.proto", fileDescriptor_customer_67035383523f7620) }

var fileDescriptor_customer_67035383523f7620 = []byte{
	// 413 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x4f, 0x8b, 0xd4, 0x40,
	0x10, 0xc5, 0xe9, 0xcc, 0xff, 0x5a, 0x19, 0x9c, 0x62, 0xd0, 0x18, 0x04, 0x43, 0x0e, 0x12, 0x44,
	0x12, 0x1d, 0x05, 0xd1, 0xdb, 0xb2, 0xa0, 0x1e, 0x3c, 0x45, 0xef, 0xd2, 0x9b, 0x94, 0xb3, 0x8d,
	0x93, 0x74, 0x4c, 0xd7, 0x28, 0xe3, 0xd1, 0xab, 0x47, 0xcf, 0x7e, 0x2a, 0x8f, 0x5e, 0xfd, 0x20,
	0x92, 0x4e, 0xb7, 0xe3, 0x32, 0xb7, 0x7a, 0x55, 0xaf, 0xaa, 0xf9, 0xbd, 0x86, 0x65, 0xb9, 0x37,
	0xac, 0x6b, 0xea, 0xb2, 0xb6, 0xd3, 0xac, 0x71, 0xee, 0x75, 0x74, 0x6f, 0xab, 0xf5, 0x76, 0x47,
	0xb9, 0xed, 0x5f, 0xee, 0x3f, 0xe4, 0xac, 0x6a, 0x32, 0x2c, 0xeb, 0x76, 0xb0, 0x46, 0x77, 0x9d,
	0x41, 0xb6, 0x2a, 0x97, 0x4d, 0xa3, 0x59, 0xb2, 0xd2, 0x8d, 0x19, 0xa6, 0xc9, 0xef, 0x00, 0x66,
	0x05, 0x7d, 0xda, 0x93, 0x61, 0x5c, 0x42, 0xa0, 0xaa, 0x50, 0xc4, 0x22, 0x9d, 0x14, 0x81, 0xaa,
	0x10, 0x61, 0xdc, 0xc8, 0x9a, 0xc2, 0x20, 0x16, 0xe9, 0xa2, 0xb0, 0x35, 0xae, 0x61, 0x42, 0xb5,
	0x54, 0xbb, 0x70, 0x64, 0x9b, 0x83, 0xe8, 0xbb, 0xed, 0x95, 0x6e, 0x28, 0x1c, 0x0f, 0x5d, 0x2b,
	0xf0, 0x19, 0x2c, 0x64, 0x55, 0x75, 0x64, 0x0c, 0x99, 0x70, 0x12, 0x8f, 0xd2, 0xb3, 0xcd, 0x9d,
	0xec, 0x1f, 0x88, 0x7b, 0x35, 0x3b, 0x1f, 0x2c, 0xc5, 0xd1, 0x8b, 0xcf, 0x01, 0xca, 0x8e, 0x24,
	0x53, 0xf5, 0x5e, 0x72, 0x38, 0x8d, 0x45, 0x7a, 0xb6, 0x89, 0xb2, 0x81, 0x23, 0xf3, 0xa0, 0xd9,
	0x3b, 0x0f, 0x5a, 0x2c, 0x9c, 0xfb, 0x9c, 0xa3, 0xef, 0x02, 0x66, 0xee, 0x22, 0xde, 0x82, 0xa9,
	0xe1, 0x8e, 0x88, 0x2d, 0xd3, 0xa2, 0x70, 0xaa, 0xe7, 0x2a, 0x15, 0x1f, 0x3c, 0x57, 0x5f, 0xf7,
	0x04, 0x86, 0x25, 0x93, 0xe7, 0xb2, 0x02, 0x6f, 0xc2, 0xe8, 0xab, 0x6a, 0x1d, 0x55, 0x5f, 0xe2,
	0x43, 0x58, 0x29, 0xf3, 0xf6, 0x4a, 0xb5, 0xad, 0x6a, 0xb6, 0xee, 0xa1, 0x70, 0x12, 0x8b, 0x74,
	0x5e, 0x9c, 0x0e, 0x92, 0xa7, 0x30, 0x2f, 0xc8, 0xb4, 0xba, 0x31, 0x74, 0x92, 0x6e, 0x08, 0x33,
	0xb3, 0x2f, 0xcb, 0x7e, 0x3f, 0xb0, 0xfb, 0x5e, 0x26, 0xf7, 0x01, 0xde, 0x28, 0xc3, 0x2f, 0xd5,
	0x8e, 0xa9, 0xeb, 0x7d, 0x1f, 0xe9, 0xf0, 0x45, 0x77, 0x95, 0xc3, 0xf0, 0x72, 0xf3, 0x53, 0xc0,
	0xfc, 0xc2, 0xc5, 0x89, 0xaf, 0x60, 0xdc, 0x2f, 0xe1, 0xfa, 0x98, 0xf0, 0xf1, 0x48, 0xb4, 0x3a,
	0xc9, 0x3d, 0x59, 0x7f, 0xfb, 0xf5, 0xe7, 0x47, 0xb0, 0xc4, 0x1b, 0xf9, 0xe7, 0xc7, 0xb9, 0x9f,
	0x3e, 0x12, 0xf8, 0x1a, 0xa6, 0x17, 0x36, 0x4e, 0x3c, 0x5d, 0x8a, 0xf0, 0xff, 0xd6, 0x00, 0x96,
	0xdc, 0xb6, 0x87, 0x56, 0xc9, 0xb5, 0x43, 0x2f, 0xc4, 0x83, 0xcb, 0xa9, 0xfd, 0xaa, 0x27, 0x7f,
	0x03, 0x00, 0x00, 0xff, 0xff, 0x85, 0x05, 0xf5, 0x32, 0xbd, 0x02, 0x00, 0x00,
}
